CREATE DATABASE IF NOT EXISTS sed;
USE sed;

CREATE TABLE IF NOT EXISTS users(
    User_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);